/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.data.type;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryReference;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;
import org.spongepowered.api.world.server.ServerWorld;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.WORLD)
public final class CatTypes {

    public static final RegistryReference<CatType> ALL_BLACK = CatTypes.key(ResourceKey.minecraft("all_black"));

    public static final RegistryReference<CatType> BLACK = CatTypes.key(ResourceKey.minecraft("black"));

    public static final RegistryReference<CatType> BRITISH_SHORTHAIR = CatTypes.key(ResourceKey.minecraft("british_shorthair"));

    public static final RegistryReference<CatType> CALICO = CatTypes.key(ResourceKey.minecraft("calico"));

    public static final RegistryReference<CatType> JELLIE = CatTypes.key(ResourceKey.minecraft("jellie"));

    public static final RegistryReference<CatType> PERSIAN = CatTypes.key(ResourceKey.minecraft("persian"));

    public static final RegistryReference<CatType> RAGDOLL = CatTypes.key(ResourceKey.minecraft("ragdoll"));

    public static final RegistryReference<CatType> RED = CatTypes.key(ResourceKey.minecraft("red"));

    public static final RegistryReference<CatType> SIAMESE = CatTypes.key(ResourceKey.minecraft("siamese"));

    public static final RegistryReference<CatType> TABBY = CatTypes.key(ResourceKey.minecraft("tabby"));

    public static final RegistryReference<CatType> WHITE = CatTypes.key(ResourceKey.minecraft("white"));

    private CatTypes() {
    }

    public static Registry<CatType> registry(final ServerWorld world) {
        return world.registry(RegistryTypes.CAT_TYPE);
    }

    private static RegistryReference<CatType> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.CAT_TYPE, location).asReference();
    }
}
